const actionTypes = {
  ADD_MOVIE: 'ADD_MOVIE',
  EDIT_MOVIE: 'EDIT_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  GET_MOVIE: 'GET_MOVIE',
  FILTER_BY_GENRE: 'FILTER_BY_GENRE',
  SORT_BY_DATE_AND_RATING: 'SORT_BY_DATE_AND_RATING',
};

export default actionTypes;
