const actionTypes = {
  ADD_MOVIE: 'ADD_MOVIE',
  EDIT_MOVIE: 'EDIT_MOVIE',
  DELETE_MOVIE: 'DELETE_MOVIE',
  GET_MOVIE: 'GET_MOVIE',
  SORT_BY_GENRE: 'SORT_BY_GENRE',
  FILTERING_MOVIE: 'FILTERING_MOVIE',
};

export default actionTypes;
